### ISSUE TITLE
Filebot not working

### ISSUE THREAD

**Issue by EpiqSty** [ghostserverd/mediaserver-docker#17]
Hi,

Actually I never saw it working,   but maybe you can suggest what to check. 
I've set folders structure accordingly to the Readme, but Filebot shows me such error:
`Invalid usage: output folder [/share/media] must be separate from input folder [dir:/share, kind:multi, title:null, label:null]`
and as well in the logs:
`2020/10/31 03:37:59 exec error:  exit status 4`

By working i presume, that if something already exists in `/downloads/complete/sonarr/` for example, hard links should be created by Filebot at the `/share/media/tv'. But seems like i'm missing something to make it works ;) Could you please advice, how to check that?

Thanks in advance!

**Comment by EpiqSty** [comment]
Went trough the Readme again, and seems something is missing here: https://github.com/ghostserverd/mediaserver-docker/blame/master/README.md#L61:
```
configured to call `filebot` container on torrent completion
```
i.e. I can't find anything in the transmission config for that purpose. How it should supposed to be handled?

**Comment by ghostserverd** [comment]
The default config for transmission will call `transmission-postprocess.sh` which makes the filebot request

https://github.com/ghostserverd/docker-transmission-ghost/blob/master/settings.json#L56

https://github.com/ghostserverd/docker-transmission-ghost/blob/master/transmission-postprocess.sh


What does your directories configuration look like? This part in the `.env` file

```
# ======== directories ========
CONFIG_DIR=/some/directory/media_server/config
DOWNLOAD_DIR=/some/directory/media_server/downloads
MEDIA_DIR=/some/directory/media_server/media
TV_DIR=/some/directory/media_server/media/TV Shows
MOVIES_DIR=/some/directory/media_server/media/Movies
### base dir should be a directory that contains both downloads and media to take advantage of hardlinks
BASE_DIR=/some/directory/media_server
```

This message is telling us that the output folder must not be inside the input folder:

https://www.filebot.net/forums/viewtopic.php?t=9528

Make sure your `MEDIA_DIR` is not inside of your `DOWNLOAD_DIR`

**Comment by EpiqSty** [comment]
Yes, that part for missing in my `settings.json` - thanks, now it is working!

**Comment by trepatudo** [comment]
`# ======== directories ========
CONFIG_DIR=/media/server/config
DOWNLOAD_DIR=/media/server/downloads
MEDIA_DIR=/media/server/media
TV_DIR=/media/server/media/TV Shows
MOVIES_DIR=/media/server/media/Movies
### base dir should be a directory that contains both downloads and media to take advantage of hardlinks
BASE_DIR=/media/server`

I have the same error and I don't see any error on my folder structure.
