### ISSUE TITLE
.env_sample missing from clone

### ISSUE THREAD

**Issue by ploughpuff** [ghostserverd/mediaserver-docker#19]
The first instruction under [Build your env file](https://github.com/ghostserverd/mediaserver-docker/blob/master/README.md#build-your-env-file) is `cp .env_sample .env`, however, the sample env file is not available after cloning the repo.  Is it being ignored perhaps?

**Comment by ghostserverd** [comment]
```
# git clone https://github.com/ghostserverd/mediaserver-docker.git
# cd mediaserver-docker
# ls -a
.  ..  .env_sample  .git  .gitignore  README.md  docker-compose.yml
```

Are you not showing hidden files? File names prepended with a `.` are often treated as hidden and don't show up unless you take extra steps to show hidden files.

**Comment by ploughpuff** [comment]
Ha! yes. embarrassing. I missed the -a switch!  Thank you.
