### ISSUE TITLE
Plex Auth Issue

### ISSUE THREAD

**Issue by Solarnik** [ghostserverd/mediaserver-docker#21]
When browsing to {IP}:32400/web I get the following issue.

![image](https://user-images.githubusercontent.com/38599495/104196515-dde61800-53f1-11eb-92b6-861de182821f.png)

I have tried going through and seeing if I can figure out this issue.  Every other service is working as intended.

.env
`# ======== directories ========
CONFIG_DIR=/hdd/media_server/config
DOWNLOAD_DIR=/hdd/media_server/downloads
MEDIA_DIR=/hdd/media_server/media
TV_DIR=/hdd/media_server/media/TV Shows
MOVIES_DIR=/hdd/media_server/media/Movies
### base dir should be a directory that contains both downloads and media to take advantage of hardlinks
BASE_DIR=/hdd/media_server

# ======== user ========
PUID=1000
PGID=1000
TIMEZONE=America/New_York

# ======== transmission ========
TRANS_WEBUI_USER={user}
TRANS_WEBUI_PASS={pass}
TRANS_WEBUI_PORT=5656
TRANS_CONNECTION_PORT=51413
### retain torrents for up to this many seconds
TRANS_MAX_RETENTION=2592000
### retain torrents until they reach this ratio
TRANS_MAX_RATIO=10

# ======== filebot ========
FILEBOT_PORT=7676
### results in file names like "The Expanse - S02E07 - The Seventh Man - HD.mkv"
FILEBOT_FORMAT={plex} - {hd}
### prefer titles from the last 30 days but fall back to any title if there are none recent enough
FILEBOT_FILTER=any{ age < 30 }{ true } || !model.any{ it.age < 30 && it.age != null }
### duplicate will fall back to copy if hardlink fails. set to "hardlink" to confirm if hardlinks are working
FILEBOT_ACTION=duplicate
### filebot will intelligently decide whether or not to replace an existing copy
FILEBOT_CONFLICT=auto
### defaults to TheTVDB but TheTVDB has been having issues for most of 2020
FILEBOT_SERIES_DB=TheMovieDB::TV
FILEBOT_ANIME_DB=AniDB
FILEBOT_MOVIE_DB=TheMovieDB
FILEBOT_MUSIC_DB=ID3
### not currently functional
OPEN_SUB_USER=[REPLACEME]
### not currently functional
OPEN_SUB_PASS=[REPLACEME]

# ======== nzbget ========
NZBGET_PORT=7890
NZBGET_WEB_USER={user}
NZBGET_WEB_PASS={pass}
### don't change these unless you really know what you're doing
NZBGET_MAIN_DIR=/downloads/nzb
NZBGET_SCRIPT_DIR=/usr/local/bin

# ======== sonarr ========
SONARR_PORT=8989

# ======== radarr ========
RADARR_PORT=7878

# ======== bazaar ========
BAZARR_PORT=6767

# ======== jackett ========
JACKETT_PORT=9117

# ======== plex ========
### install trakt and subzero but you might need Kitana to see the UI
PLUGIN_LIST=trakt subzero Kitana
PLEX_WEB_PORT=32400

# ======== tautulli ========
TAUTULLI_PORT=8181

# ======== heimdall ========
HEIMDALL_PORT=8888
HEIMDALL_SSL_PORT=4444

# ======== wireguard ========
### the local network of your host machine to allow access to the service from the local network. required for VPN port forwarding.
LOCAL_NETWORK=192.168.0.0/24

# ======== letsencrypt ========
### a domain like "somedomain.com"
LE_HOSTNAME=[REPLACEME]
### an email at your above domain like "me@somedomain.com"
LE_EMAIL=[REPLACEME]
### a comma separated list of subdomains to set up letsencrypt certs for
LE_SUBDOMAINS=r,s,t,n,p,m,u,h,b
NGINX_USER=user
### not currently functional
NGINX_PASS=[REPLACEME]

# ======== netdata ========
NETDATA_PORT=19999

# ======== portainer ========
PORTAINER_PORT=9000`

**Comment by valedmar** [comment]
I am experiencing the same issue.

**Comment by Mixie-12** [comment]
I am also having the same issue

**Comment by Mixie-12** [comment]
**FIX!**

You need to access the server over  127.0.0.1
Easiest method is setting up SSH port forwarding

**Comment by Mixie-12** [comment]
FIX!

You need to access the server over 127.0.0.1
Easiest method is setting up SSH port forwarding

**Comment by Solarnik** [comment]
@Mixie-12 Thank you for figuring this out. I was having to run plex outside of the docker to get around this issue, but it is working great now.

**Comment by ghostserverd** [comment]
Thanks for the fix @Mixie-12. I've updated the README to include instructions on creating an SSH tunnel to claim the server on `localhost`.

https://github.com/ghostserverd/mediaserver-docker/commit/af64932cd610776d8ddca69fe8f79b34d96e5cbb
