### ISSUE TITLE
Transmission rewrites config every restart

### ISSUE THREAD

**Issue by twavis** [ghostserverd/mediaserver-docker#27]
Any way to avoid overwriting the config/transmission/settings.json so any settings we set the last transmission session will be saved and used?

**Comment by ghostserverd** [comment]
There isn't really. The intent is that the container should be portable with your `.env` file, so persistent config changes should happen there and be used by the container to build the transmission config.

Are there any specific configurations you want to be supported?

**Comment by twavis** [comment]
I agree that it should be configured with env variables when possible but I was needing to change a lot of the defaults. Many of the other containers (radarr/sonarr/etc) persist their config changes so I didn't think it would be unexpected behavior.
