### ISSUE TITLE
NZBGet - Paths Error

### ISSUE THREAD

**Issue by Deanbau** [ghostserverd/mediaserver-docker#28]
First off - thank you so much for making this. I have an issue with a new setup - the setting looks correct however I get the following error on boot of NZBget

![image](https://user-images.githubusercontent.com/39572328/129373446-5673002e-af12-4d85-80b4-61a2b8c643e3.png)

Below I believe are the related parts of my .env

```
# ======== directories ========
CONFIG_DIR=/config
DOWNLOAD_DIR=/data/media_server/downloads
MEDIA_DIR=/data/media_server/media
TV_DIR=/data/media_server/media/TV Shows
MOVIES_DIR=/data/media_server/media/Movies
### base dir should be a directory that contains both downloads and media to take advantage of hardlinks
BASE_DIR=/data/media_server

# ======== nzbget ========
NZBGET_PORT=7890
NZBGET_WEB_USER=user
NZBGET_WEB_PASS=pass
### don't change these unless you really know what you're doing
NZBGET_MAIN_DIR=/downloads/nzb
NZBGET_SCRIPT_DIR=/usr/local/bin

```

I believe all the permission are set correctly.

Thanks

**Comment by ghostserverd** [comment]
Hey saw that you closed this. Did you get it figured out? Is there something I need to update in the readme?

**Comment by Deanbau** [comment]
Hey - It was a local permissions error. I'm pretty new to this so just did a reinstall and it worked fine. Apart from filebot not working correctly but I believe this is 100% my fault and no need for a issue post.
