### ISSUE TITLE
Media directory for Plex

### ISSUE THREAD

**Issue by gdlgiii** [ghostserverd/mediaserver-docker#3]
Media content is on NAS share and will not be hosted on local dedicated server. What is the format for network shares that are persistent?

**Comment by ghostserverd** [comment]
Hey sorry I missed this. Guess I need to check my GitHub notification settings.

You'll want to mount media directories from the NAS on whatever server you're hosting the media services with so it shows up in your filesystem as a directory.

Then you'll modify the .env file to reference the directories that you mounted your media to.

You can use a built in OS functionality like fstab or an application like autofs (what I personally use) to manage the mounts. I mount NFS shares from my NAS.

**Comment by ghostserverd** [comment]
I'm going to close this. In the future, there may be a world where we can have a container to automatically mount NFS shares or maybe even an rclone container, but that's a ways out, and it may never happen.
