### ISSUE TITLE
Interface not found in /etc/wireguard

### ISSUE THREAD

**Issue by patcfly** [ghostserverd/mediaserver-docker#31]
I've created a wgnet0.conf file using the mullvad configuration page and placed in the suggested dir /some/dir/config/wireguard

I customized .env to my environment

I have set transmission and nzbget to use network_mode and have commented out the ports section of each service.
network_mode: "service:wireguard"
   depends_on:
     - wireguard

When I run docker-compose up, everything starts except for: wireguard, which causes both transmission and nzbget to fail as they cannot find their network adapter.

I pulled logs from the wiregaurd container
docker logs --tail 50 --follow --timestamps 83062a4c8231
2022-01-20T03:12:30.503070380Z Thu Jan 20 03:12:30 UTC 2022: ---FATAL--- Interface not found in /etc/wireguard

Anything else I should look at configuring? I've been at this for two nights now.

**Comment by Mixie-12** [comment]
Is sounds like there is an issue with your mount.
Make sure your wireguard container has:
  volumes:
      - /YOUR_CONFIG_DIR/wireguard:/etc/wireguard
       - /lib/modules:/lib/modules

Also make sure the config file name is wg0.conf

**Comment by patcfly** [comment]
the docker-compose.yml file was looking for - /YOUR_CONFIG_DIR/wireguard:/etc/wireguardsu 

wireguard is in /etc/wireguard  so the dirs didn't match.

Thanks for helping me find the issue!
