### ISSUE TITLE
deluge 

### ISSUE THREAD

**Issue by albanyeye** [ghostserverd/mediaserver-docker#32]
Hello, I have a docker for delugevpn. Would that work with filebot  if I replaced transmission client?
What modifications do I need to do for that to work?
Thanks

**Comment by albanyeye** [comment]
Hey..:just found this!
Thanks!!
https://github.com/ghostserverd/docker-deluge-ghost/blob/main/deluge-postprocess.sh

**Comment by ghostserverd** [comment]
FWIW I don't use deluge myself so there might be unforeseen issues with that container. But hopefully it works for you.
