### ISSUE TITLE
Hardlink unfriendly configuration

### ISSUE THREAD

**Issue by Tryum** [ghostserverd/mediaserver-docker#35]
Hi, 

I just found your repo searching for samples of docker-based automated media servers.

One thing I figured out recently, is that data volumes between media and downloads shouldn't be separated, to allow hardlinks and atomic moves : https://trash-guides.info/Hardlinks/Hardlinks-and-Instant-Moves/

Cheers

**Comment by ghostserverd** [comment]
A note about hardlinking is in the README.

https://github.com/ghostserverd/mediaserver-docker#directories

It's up to the end-user to ensure that they have mounts / volumes set up properly to take advantage of hardlinks.

Feel free to open a PR if you think there's some improvement to be made to the documentation.

Thanks!

**Comment by Tryum** [comment]
Actually the statement is false, even if it's the same underlying filesystem, mounting separate volumes will prevent hardlinks to work as the it'll be seen as different filesystems.

**Comment by ghostserverd** [comment]
The suggestion is to mount a single volume (`/some/directory/media_server`) and then define your `downloads` and `media` directories in that single volume. I tweaked the language to try to make that clearer. If you think it could be improved, don't hesitate to open a PR.
