### ISSUE TITLE
Can't connect to Sonarr

### ISSUE THREAD

**Issue by gatsby0121** [ghostserverd/mediaserver-docker#37]
I'm not sure if this is an image issue, or just me, but all of a sudden I can't connect to sonarr, but I can connect to all the other containers.

I'm not sure how to debug this issue, but if you have any starting points, I can take a look.

**Comment by gatsby0121** [comment]
This ended up being an issue with sonarr and ubuntu.  I had to update to the latest for sonarr to work.

**Comment by ghostserverd** [comment]
Thanks for updating after you got it resolved. FWIW `ghostserverd/sonarr` gets rebuilt when linuxserver updates their container, but you might need something like [watchtower](https://github.com/containrrr/watchtower) to have it update automatically.
