### ISSUE TITLE
Can't start Plex container on host without X server

### ISSUE THREAD

**Issue by rameleu** [ghostserverd/mediaserver-docker#4]
Hi,

I'm trying to start the docker container, everything starts fine but the Plex container

Here is the error I get
`ERROR: for plex  Cannot start service plex: error gathering device information while adding custom device "/dev/dri/card0": no such file or directory
ERROR: Encountered errors while bringing up the project.`

**Comment by rameleu** [comment]
Just removing the 
`devices:
      - "/dev/dri/card0:/dev/dri/card0"
      - "/dev/dri/renderD128:/dev/dri/renderD128"`
inside docker-compose.yml does the trick!

**Comment by ghostserverd** [comment]
Can you still get hardware encoding without those devices passed through? I wouldn’t think x server would be necessary to have access to those devices. Perhaps you are missing a driver.
