### ISSUE TITLE
Non-updated watchtower container in docker-compose.yaml

### ISSUE THREAD

**Issue by parker-hemphill** [ghostserverd/mediaserver-docker#7]
I recommend using containrrr/watchtower since it receives regular updates.  The watchtower docker container your currently using hasn't been updated in > 2 years.

**Comment by ghostserverd** [comment]
Ah yes it’s been on my list for a few weeks now, but thanks for opening an issue. I should have time to update and test this week.

**Comment by ghostserverd** [comment]
https://github.com/ghostserverd/mediaserver-docker/commit/7c2da24dcb335dff375ce55eaeddba61ba151950
